version: '3.8'
services:
  app:
    image: 577638354424.dkr.ecr.ap-south-1.amazonaws.com/dev/igm-protocol-server-engine:latest  # Will be dynamically updated by Jenkins
    container_name: ${CONTAINER_NAME:-mock-server-utility}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    restart: always