services:
  app:
    image: 577638354424.dkr.ecr.ap-south-1.amazonaws.com/trv-mock_server_utility:latest
    container_name: trv-mock_server_utility
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    restart: always
