version: "3.8"

services:
  app:
    image: 577638354424.dkr.ecr.ap-south-1.amazonaws.com/fis-mock_server_utility
    container_name: fis-mock-server-utility
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    restart: always
